apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-resistent-volume-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
